SAP-43 Setup socket server and routes
Project-SAP/project-sap-backend pull request #10
Opened 2022-11-06 02:52 UTC by glitchkyle

**Description**
Added route handling for specific socket routes. Users can now join the queue and match with desired users, either "Venter" or "Listener". Users are also able to send message to their designated rooms. Users will initially be in their own rooms identified by their socket ID. Once matched, the venter and listener will be in the same room. An important thing to note is that socket entries are uniquely identified by their unique username. Routes that must be handled by the frontend can be seen in these changes, specifically "joinQueue", "leaveQueue", and "message". 

Link to JIRA ticket: https://peakashu.atlassian.net/browse/SAP-43?atlOrigin=eyJpIjoiM2JlYTk4MGEwMzcwNGFkZjljMzRlZWE0NzEzNDU2MzUiLCJwIjoiaiJ9

**How to Test**
Cannot be tested without proper chat messaging page and system

2022-11-06 03:43 UTC, CpazR requested changes
Looking good so far. Curious to see how it works once the frontend is setup.

2022-11-06 03:43 UTC, CpazR commented on src/serverApplication.ts
> +     private socketServerInit(httpServer: HTTPServer): SocketServer {
For the sake of readability, I'd put this method into a utils file.
Either its own, or in `server.utils.ts` with the express server init.

2022-11-06 03:43 UTC, CpazR commented on src/serverApplication.ts
> +                if(data.profile === "venter"){
Looks like formatting needs to be ran on the file.

2022-11-06 03:43 UTC, CpazR commented on src/serverApplication.ts
> +        io.on("connection", (socket) => {
So is this effectively a controller for socket endpoints?
Like to join the queue, would you hit `localhost:port/connection/joinQueue`?

2022-11-06 03:43 UTC, CpazR commented on src/serverApplication.ts
> +                console.log("Socket Disconnected");
Is disconnect logic not implemented yet?

2022-11-06 03:43 UTC, CpazR commented on src/serverApplication.ts
> +     private socketServerInit(httpServer: HTTPServer): SocketServer {
Actually, that method can probably be renamed since it's only setting up the express piece.

2022-11-06 03:44 UTC, CpazR commented
Also, is `src/handlers/socketHandler.ts` being used? It's empty.

2022-11-07 20:19 UTC, glitchkyle commented on src/serverApplication.ts
> +                console.log("Socket Disconnected");
It was just there for debugging purposes but I will be removing this once the PR is actually ready after testing with the frontend.

2022-11-07 20:21 UTC, glitchkyle commented on src/serverApplication.ts
> +        io.on("connection", (socket) => {
After import `socket.io-client`, you can create an instance of a socket in the frontend to connect to our socket server. 

For that `joinQueue` example, the socket instance you will create in the frontend can `emit` the `joinQueue` event and send the necessary data. You can read more about emitting events here: https://socket.io/docs/v4/client-api/#socketemiteventname-args

2022-11-24 23:37 UTC, CpazR commented
As a note, there's a vunrability in this version of `socket.io` it needs to update to `4.5.4`

2022-11-27 04:00 UTC, glitchkyle commented on src/serverApplication.ts
> +     private socketServerInit(httpServer: HTTPServer): SocketServer {
So would you like me to just rename this method? @CpazR

2022-11-27 04:03 UTC, glitchkyle commented on src/serverApplication.ts
> +                if(data.profile === "venter"){
Is there something wrong with the variable references?

2022-11-27 12:40 UTC, CpazR commented on src/serverApplication.ts
> +                if(data.profile === "venter"){
No, just the general formatting of the file, like the lack of whitespace between braces, else's being on a newline, stuff like that.
It results in unnecessary changes in PRs if the formatting rules are ran for future items.

When in doubt, always run the formatting rules.

2022-11-27 12:44 UTC, CpazR commented on src/serverApplication.ts
> +     private socketServerInit(httpServer: HTTPServer): SocketServer {
No. `socketServerInit` is clear enough.

The function in `server.utils.ts` could probably be renamed to something like `expressServerInit` or something clear enough. Just to distinguish the two since they're both initializing separate servers.

2022-11-28 18:17 UTC, CpazR requested changes
Almost done, I think. Just had one thing I wanted clarification on.

2022-11-28 18:17 UTC, CpazR commented on src/serverApplication.ts
> +    private socketServerInit(httpServer: HTTPServer): SocketServer {
I still think this function should be moved into `server.utils.ts` Is there a reason it should stay here?

2022-11-28 18:18 UTC, CpazR commented
Also the `socket.io` version still need to be bumped to 4.5.4

2022-12-01 06:00 UTC, CpazR approved these changes
Would like to see the socket server initialization moved, but that be done later.

2022-12-02 23:54 UTC, grahamstephens approved these changes
looking good

2022-12-04 20:12 UTC, merged