added signup
Project-SAP/project-sap-backend pull request #8
Opened 2022-11-03 00:15 UTC by grahamstephens

see user.db.ts and user.service.ts for the main problems. they contain the functions insertOne and newUser, respectively

2022-11-03 01:05 UTC, CpazR commented on src/data-access/user.db.ts
> +            /**
Looks like you need to run formatting on the file.

2022-11-03 01:05 UTC, CpazR requested changes

2022-11-03 01:05 UTC, CpazR commented on src/data-access/user.db.ts
> +     public insertOne(doc: {}): Promise<T> {
The type could probably be `any` here, since this is being done generically.

2022-11-03 03:05 UTC, CpazR commented on src/controller/auth.controller.ts
> +import { STATUS_CODES } from 'http';
Both of these imports can be removed.

2022-11-03 03:12 UTC, CpazR commented on src/controller/auth.controller.ts
> +        if (user) {
Don't know why this works. This check should be removed.

2022-11-03 03:13 UTC, CpazR commented on src/controller/auth.controller.ts
> +        this.userService.newUser(signupRequest.email, signupRequest.password);
Don't forget to call `next()` after this call. Otherwise, the endpoint will hang.

2022-11-03 03:44 UTC, CpazR commented
`package-lock.json ` needs to be reverted. I think its what's causing the failing builds.

2022-11-04 01:04 UTC, CpazR commented on src/controller/auth.controller.ts
> +    public async userSignup(request: Request, response: Response, next: any) {
While not required at this point, due to time, I **would** like to see tests written for this endpoint.

If you can pick up on it, it should be an easy set of tests.
At least take a look in `auth.controller.test.ts`

2022-11-04 03:54 UTC, CpazR approved these changes
Going ahead and approving this.

2022-11-04 19:31 UTC, glitchkyle commented on src/data-access/user.db.ts
> +    public create(doc: any): Promise<any> {
Can you update the documentation for this?

2022-11-04 19:32 UTC, glitchkyle commented on src/controller/auth.controller.ts
> +        this.userService.newUser(signupRequest.email, signupRequest.password);
Can you send a 201 response for this just for the frontend to load an ok or error?

2022-11-04 19:41 UTC, glitchkyle requested changes
Looking good! Just a few changes like we mentioned in Discord#general. Requests I made in the comments should be easy.

2022-11-06 01:18 UTC, CpazR commented on src/controller/auth.controller.ts
> +        this.userService.newUser(signupRequest.email, signupRequest.password);
Does it not already? I thought `next()` defaults to an `OK` response.

I haven't done integration testing on this for the record.

2022-11-06 02:15 UTC, glitchkyle commented on src/controller/auth.controller.ts
> +        this.userService.newUser(signupRequest.email, signupRequest.password);
Will it be sending a 200 or a 201 response? That might make a difference when handling in the frontend. I'm also wondering if we need to send a response if we failed to create a user due to a 500 server error.

2022-11-06 04:05 UTC, CpazR commented on src/controller/auth.controller.ts
> +        this.userService.newUser(signupRequest.email, signupRequest.password);
You're right.

@grahamstephens
The way you would do this is await on `.newUser` and check the returned user. 
If it exists, return a 201 status. Otherwise return a 500 error with a simple "failed to create user" message.

2022-11-09 20:24 UTC, CpazR commented
Also as discussed, we should be accepting a username from the frontend.

2022-11-11 19:11 UTC, CpazR requested changes
Only a few smaller issues that need addressed, but the username implementation is looking good so far.

2022-11-11 19:11 UTC, CpazR commented on src/controller/auth.controller.ts
> +        next();
I think this is an incomplete response. Wasn't able to finish this since we ran out of time on Thursday.
```
response.send({email: userCreated.email, userName: userCreated.userName});
response.status(201).end();
```

But I don't think the `next();` will be needed here.

2022-11-12 07:05 UTC, CpazR commented on src/controller/auth.controller.ts
> +        const newUsername = `${signupRequest.userName}#${Math.random() * 1000}`
`Math.Random()` will not do enough to grantee a unique username.

I would recommend using the date time and the username itself in tandem with `bcrypt` to make a custom hash function.

Here's a good resource to reference:
https://security.stackexchange.com/questions/218044/how-to-generate-short-fixed-length-cryptographic-hashes

2022-11-12 18:07 UTC, glitchkyle commented on src/service/user.service.ts
> +    public async findByUsername(email: string): Promise<User> {
It's find by username but the parameter is called email?

2022-11-12 18:11 UTC, glitchkyle commented on src/controller/auth.controller.ts
> +        const newUsername = `${signupRequest.userName}#${Math.random() * 1000}`
^^ This is a great solution compared to my "use the number of users currently in the database"

2022-11-12 18:13 UTC, glitchkyle commented on src/controller/auth.controller.ts
> +        const testName: User = await this.userService
What's the purpose of testName here? I see that you are trying to double check the creation but we won't need it if we always guarantee a unique username by, for example, using @CpazR's solution

2022-11-12 18:21 UTC, glitchkyle commented on src/controller/auth.controller.ts
> +        response.status(201).end();
These are two different responses here, tried it out in Postman. `end` actually is used to quickly end the response without any data. What you could do is `response.status(201).send({email: userCreated.email, userName: userCreated.userName});`

2022-11-12 18:21 UTC, glitchkyle requested changes
Almost there! Just a few minor changes.

2022-11-15 17:52 UTC, CpazR commented on src/controller/auth.controller.ts
> +        const newUsername = `${signupRequest.userName}#${Math.random() * 1000}`
If bcrypt doesn't allow hashing of multiple values for whatever reason, we might be able to get away with just the datetime.

https://stackoverflow.com/questions/32649704/how-to-generate-hash-from-timestamp

2022-11-15 19:26 UTC, CpazR commented on src/controller/auth.controller.ts
> +        response.status(201).end();
You're right. I missed that. `.end()` isn't needed here.

2022-11-17 15:33 UTC, CpazR commented on src/controller/auth.controller.ts
> +        const newUsername = `${signupRequest.userName}#${Math.random() * 1000}`
As per discussion Tuesday, to get things moving we'll revert to the `Math.randomize()` approach.

I definitely want to come back to this, though. I still don't think it will be a scalable solution.

2022-11-17 17:54 UTC, CpazR commented on src/controller/auth.controller.ts
> +        const testName: User = await this.userService
Should probably be renamed to something like `existingUser` so code can be self-documenting.

But as noted above, we'll stick with this for now, but this should get refactored at some point, this is going to put unnecessary load on the database.

2022-11-17 17:55 UTC, CpazR commented on src/controller/auth.controller.ts
> +        response.status(201);
This can be a chained call before `.send(...)`

So `response.status(201).send(...);`

2022-11-17 17:57 UTC, CpazR commented on src/data-access/user.db.ts
> +    public create(doc: any): Promise<any> {
Documentation should say something to the extent of:

```
Creates a new document in the database and returns a promise of the resulting json object
```

Or at least along those lines. Not certain of the specifics.

2022-11-17 17:59 UTC, CpazR commented on src/service/user.service.ts
> +    public async newUser(email: string, password: string, userName: string): Promise<User> {
No changes required here, just wanted to say that it's smart to move the username generation to the service.

If we do decide to use a hashing approach later, it should probably be its own private function in the service, but this works for now.

2022-11-17 19:23 UTC, CpazR approved these changes
Going ahead and approving this. Need a ticket for documentation fixes.

2022-11-17 19:37 UTC, glitchkyle approved these changes
LGTM!

2022-11-17 19:37 UTC, merged